services:
  redis:
    image: redis:8.0-rc1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis_data:/data
    restart: unless-stopped

networks:
  my_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
